crud/config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'

  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :dogs
  # get 'dogs/index'
  # get 'dogs/show'
  # get 'dogs/new'
  # get 'dogs/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

crud/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

crud/app/models/dog.rb
class Dog < ApplicationRecord
end

crud/app/models/user.rb
class User < ApplicationRecord
end

crud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?
    helper_method :current_user

    def current_user
        User.find_by(id: session[:user_id])  
    end

    def logged_in?
        !current_user.nil?
    end
end

crud/app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :current_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show

  end

  def new
    @dog = Dog.new
  end

  def create
    dog = Dog.create(dog_params)

    redirect_to dog_path(dog)
  end

  def edit

  end

  def update
    @dog.update(dog_params)

    redirect_to dog_path(@dog)
  end

  def destroy
    @dog.destroy

    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :motto)
  end

  def current_dog
    @dog = Dog.find(params[:id])
  end

end

crud/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def welcome
  end

  def new
  end
  
  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session.clear
    redirect_to '/login'
  end
end

crud/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else 
      render :new
    end
  end

  def show
  end

  def edit
    if !logged_in? || !@user
      redirect_to root_path
    end
  end
      
  def update
    if @user
      @user.update(user_params)

      if @user.errors.any?
        render "edit"
      else
        redirect_to user_path(@user)
      end
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

  def set_user
    @user = User.find_by_id(params[:id])
  end
end

crud/app/helpers/application_helper.rb
module ApplicationHelper
end

crud/app/helpers/dogs_helper.rb
module DogsHelper
end

crud/app/helpers/sessions_helper.rb
module SessionsHelper
end

crud/app/helpers/users_helper.rb
module UsersHelper
end

crud/app/views/dogs/edit.html.erb
<h1>Dogs#edit</h1>
<p>Find me in app/views/dogs/edit.html.erb</p>



<h3>Update Dog Details</h3>
<%= form_with model: @dog do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :motto, placeholder: "motto" %>
  <%= form.submit %>
<% end %>

crud/app/views/dogs/index.html.erb
<%# <ul>
    <% @dogs.each do |dog|%>
        <%# <li><%= link_to dog.name, dog_path(dog) %></li>
    <%# <% end %>
<%# </ul> %> 


<table>
  <% @dogs.each do |dog| %>
    <tr>
      <td><%= link_to dog.name, dog_path(dog) %></td>
      <td><%= button_to 'Edit', edit_dog_path(dog), method: 'get'%></td>
      <td><%= button_to 'Remove', dog_path(dog), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Dog", new_dog_path %>

crud/app/views/dogs/new.html.erb
<h1>Dogs#new</h1>
<p>Find me in app/views/dogs/new.html.erb</p>



<h3>Create a Dog</h3>
<%= form_with model: @dog do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :motto, placeholder: "motto" %>
  <%= form.submit %>
<% end %>

<!-- <%= form_for @dog do |form| %>
  <%= form.text_field :name, placeholder: 'name' %>
  <%= form.text_field :motto, placeholder: 'motto' %>
  <%= form.submit %>
<% end %> -->

crud/app/views/dogs/show.html.erb
<h1>Dogs#show</h1>
<p>Find me in app/views/dogs/show.html.erb</p>



<%= link_to 'Remove', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>

<h1><%= @dog.name %></h1>
<h4>"<%= @dog.motto %>"</h4>

crud/app/views/layouts/_nav.erb
./app/views/layouts/_nav.erb
<% if !logged_in? %>
  <%= link_to "Login", login_path %>
  <%= link_to "Sign Up", new_user_path %>
<% else %>
  <%= link_to "Log Out", logout_path, method: :delete %>
<% end %>

crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapprails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/nav' %>
  <%= yield %>
  </body>
</html>

crud/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

crud/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

crud/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

crud/app/views/users/new.html.erb
<h1>Would you like to Sign Up?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :username %><br>
  <%= f.text_field :username, autofocus: true %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.submit "Sign Up" %>
<% end %>

crud/app/views/users/show.html.erb
<h1>Welcome <%= current_user.username %></h1>
<%= link_to "Edit Account", edit_user_path(current_user) %>
<%= link_to "Delete Account", current_user, data: { confirm: "Are you sure?" }, method: :delete %>

crud/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>